### ISSUE TITLE
Message": "No HTTP resource was found that matches the request URI 'https://eu.linnworks.net/api/Inventory/AddImageToItem'.

### ISSUE THREAD

**Issue by emihir0** [LinnSystems/LinnworksNetSDK#5]
And some other APIs seem to be no longer working. Is there any up to date list I can check out to see which APIs are still working and which are not?

**Comment by LinnSystems** [comment]
Hi emihir0,

AddImageToItem is an API call that was added to the documentation as a preparation for a release shortly. It should be available soon.

Issues should be raised for issues with the code available through Github, rather than issues with the service itself (For this you can contact us through our ticketing system on Linnworks.net) as this allows us to get to them quicker and give you a better support experience.

I'll close this for now, and if you have any further questions please contact us via the ticketing system.
